manually import dataprovider
needed to run the analyze_ticker() function in the notebook https://www.freqtrade.io/en/latest/strategy_analysis_example/#load-and-run-strategy

```# Load strategy using values set above
from freqtrade.resolvers import StrategyResolver
strategy = StrategyResolver.load_strategy(config)

# Generate buy/sell signals using strategy
df = strategy.analyze_ticker(candles, {'pair': pair})
df.tail()```

Otherwise, it generates the following error:

```AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_63536/2170170204.py in <module>
      4 
      5 # Generate buy/sell signals using strategy
----> 6 df = strategy.analyze_ticker(candles, {'pair': pair})
      7 df.tail()

~/adam/envs/py37/lib/python3.7/site-packages/freqtrade/strategy/interface.py in analyze_ticker(self, dataframe, metadata)
    471         """
    472         logger.debug("TA Analysis Launched")
--> 473         dataframe = self.advise_indicators(dataframe, metadata)
    474         dataframe = self.advise_buy(dataframe, metadata)
    475         dataframe = self.advise_sell(dataframe, metadata)

~/adam/envs/py37/lib/python3.7/site-packages/freqtrade/strategy/interface.py in advise_indicators(self, dataframe, metadata)
    843             return self.populate_indicators(dataframe)  # type: ignore
    844         else:
--> 845             return self.populate_indicators(dataframe, metadata)
    846 
    847     def advise_buy(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

~/personal/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py in populate_indicators(self, dataframe, metadata)
   4631 
   4632         if self.has_BTC_info_tf:
-> 4633             btc_info_tf = self.dp.get_pair_dataframe(btc_info_pair, self.info_timeframe_1h)
   4634             btc_info_tf = self.info_tf_btc_indicators(btc_info_tf, metadata)
   4635             dataframe = merge_informative_pair(dataframe, btc_info_tf, self.timeframe, self.info_timeframe_1h, ffill=True)

AttributeError: 'NostalgiaForInfinityNext' object has no attribute 'dp'```